#name: Template
#
#on:
#  push:
#    branches: [ prod, staging ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-18.04
#
#    services:
#      mysql:
#        image: mysql:5.7
#        env:
#          MYSQL_ROOT_PASSWORD: test_pass
#        ports:
#          - 3306
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: nelonoel/branch-name@v1
#
#      - name: Validate composer.json and composer.lock
#        run: composer validate
#
#      - name: Get composer version
#        id: composer-version
#        run: echo "::set-output name=version::$(cat composer.json | jq -r .version)"
#
#      - name: Install Composer dependencies
#        run: composer install
#
#      - name: Check composer installed
#        run: composer --version
#
#      - name: Publish to Registry
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: "kakadu-dev/symfony-microservice-template/template"
#          tags: "latest-${{ env.BRANCH_NAME }},${{ steps.composer-version.outputs.version}}-${{ env.BRANCH_NAME }}"
#          dockerfile: Dockerfile-rpc
#          context: ${{ env.WORK_DIR }}
#          buildoptions: "--compress --force-rm --no-cache"
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
